package pasutijumsrestorana;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Registresana extends javax.swing.JFrame {

    /**
     * Creates new form Registresana
     */
    public Registresana() {
        initComponents(); 
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reģistrēšana = new javax.swing.JDialog();
        registrLab1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        vardsLab3 = new javax.swing.JLabel();
        vardsText3 = new javax.swing.JTextField();
        uzvardsLab3 = new javax.swing.JLabel();
        uzvardsText3 = new javax.swing.JTextField();
        talrunisLab3 = new javax.swing.JLabel();
        talrunisText3 = new javax.swing.JTextField();
        pastsLab4 = new javax.swing.JLabel();
        pastsText4 = new javax.swing.JTextField();
        paroleLab4 = new javax.swing.JLabel();
        paroleText4 = new javax.swing.JTextField();
        registrBut3 = new javax.swing.JButton();
        atceltBut1 = new javax.swing.JButton();
        Ielogošana = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        pastsLab2 = new javax.swing.JLabel();
        pastsText2 = new javax.swing.JTextField();
        paroleLab2 = new javax.swing.JLabel();
        paroleText2 = new javax.swing.JTextField();
        ielogBut2 = new javax.swing.JButton();
        atceltBut = new javax.swing.JButton();
        ielogotiesLab = new javax.swing.JLabel();
        Galvenais_logs = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        edienkarteBut = new javax.swing.JButton();
        edienumekBut = new javax.swing.JButton();
        pasutgrozsBut = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Ēdienkarte = new javax.swing.JDialog();
        edienkarteLab = new javax.swing.JLabel();
        atpBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edienkarteTable = new javax.swing.JTable();
        idedienamLab = new javax.swing.JLabel();
        uzgrozuBut = new javax.swing.JButton();
        idedienamText = new javax.swing.JTextField();
        Pasūtījuma_grozs = new javax.swing.JDialog();
        pasutijumaGrozsLab = new javax.swing.JLabel();
        atpBut4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pasutijumaGrozs = new javax.swing.JTable();
        summaLab = new javax.swing.JLabel();
        maksatBut = new javax.swing.JButton();
        Ēdienu_meklēšana = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        ednosaukumsLab = new javax.swing.JLabel();
        ednosaukumsText = new javax.swing.JTextField();
        saglabatBut = new javax.swing.JButton();
        atpBut1 = new javax.swing.JButton();
        edienaNosaukumsLab = new javax.swing.JLabel();
        Ēdienu_pievienošana = new javax.swing.JDialog();
        edPievienosanaLab = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        edNosaukumsLab = new javax.swing.JLabel();
        edNosaukumsText = new javax.swing.JTextField();
        aprakstsLab = new javax.swing.JLabel();
        aprakstsText = new javax.swing.JTextField();
        cenaLab = new javax.swing.JLabel();
        cenaText = new javax.swing.JTextField();
        mekletBut1 = new javax.swing.JButton();
        atpBut2 = new javax.swing.JButton();
        Ēdienu_rediģēšana = new javax.swing.JDialog();
        edRedigesanaLab = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jaunaedNosaukumsLab = new javax.swing.JLabel();
        jaunaedNosaukumsText = new javax.swing.JTextField();
        jaunsAprakstsLab = new javax.swing.JLabel();
        jaunsAprakstsText = new javax.swing.JTextField();
        jaunaCenaLab = new javax.swing.JLabel();
        jaunaCenaText = new javax.swing.JTextField();
        redigetBut = new javax.swing.JButton();
        atpBut3 = new javax.swing.JButton();
        laipniLudzamLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ielogBut = new javax.swing.JButton();
        registrBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Reģistrēšana.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Reģistrēšana.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ReģistrēšanaWindowClosing(evt);
            }
        });

        registrLab1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrLab1.setForeground(new java.awt.Color(255, 153, 153));
        registrLab1.setText("Reģistrēšana");

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        vardsLab3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vardsLab3.setForeground(new java.awt.Color(255, 153, 153));
        vardsLab3.setText("Vārds:");

        vardsText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vardsText3ActionPerformed(evt);
            }
        });

        uzvardsLab3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uzvardsLab3.setForeground(new java.awt.Color(255, 153, 153));
        uzvardsLab3.setText("Uzvārds:");

        uzvardsText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uzvardsText3ActionPerformed(evt);
            }
        });

        talrunisLab3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        talrunisLab3.setForeground(new java.awt.Color(255, 153, 153));
        talrunisLab3.setText("Talrunis:");

        talrunisText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talrunisText3ActionPerformed(evt);
            }
        });

        pastsLab4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pastsLab4.setForeground(new java.awt.Color(255, 153, 153));
        pastsLab4.setText("E-Pasts:");

        pastsText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastsText4ActionPerformed(evt);
            }
        });

        paroleLab4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paroleLab4.setForeground(new java.awt.Color(255, 153, 153));
        paroleLab4.setText("Parole:");

        paroleText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paroleText4ActionPerformed(evt);
            }
        });

        registrBut3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrBut3.setForeground(new java.awt.Color(255, 153, 153));
        registrBut3.setText("Reģistrēties");
        registrBut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrBut3ActionPerformed(evt);
            }
        });

        atceltBut1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atceltBut1.setForeground(new java.awt.Color(255, 153, 153));
        atceltBut1.setText("Atcelt");
        atceltBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atceltBut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                            .addComponent(vardsLab3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(vardsText3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(paroleLab4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(paroleText4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                            .addComponent(registrBut3)
                            .addGap(18, 18, 18)
                            .addComponent(atceltBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uzvardsLab3)
                            .addComponent(talrunisLab3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(talrunisText3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uzvardsText3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pastsLab4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pastsText4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vardsLab3)
                    .addComponent(vardsText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uzvardsLab3)
                    .addComponent(uzvardsText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(talrunisText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talrunisLab3))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastsText4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastsLab4))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paroleText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paroleLab4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrBut3)
                    .addComponent(atceltBut1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReģistrēšanaLayout = new javax.swing.GroupLayout(Reģistrēšana.getContentPane());
        Reģistrēšana.getContentPane().setLayout(ReģistrēšanaLayout);
        ReģistrēšanaLayout.setHorizontalGroup(
            ReģistrēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReģistrēšanaLayout.createSequentialGroup()
                .addGroup(ReģistrēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReģistrēšanaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReģistrēšanaLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(registrLab1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ReģistrēšanaLayout.setVerticalGroup(
            ReģistrēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReģistrēšanaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(registrLab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Ielogošana.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Ielogošana.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                IelogošanaWindowClosing(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pastsLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pastsLab2.setForeground(new java.awt.Color(255, 153, 153));
        pastsLab2.setText("E-Pasts:");

        pastsText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastsText2ActionPerformed(evt);
            }
        });

        paroleLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paroleLab2.setForeground(new java.awt.Color(255, 153, 153));
        paroleLab2.setText("Parole:");

        paroleText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paroleText2ActionPerformed(evt);
            }
        });

        ielogBut2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ielogBut2.setForeground(new java.awt.Color(255, 153, 153));
        ielogBut2.setText("Ielogoties");
        ielogBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ielogBut2ActionPerformed(evt);
            }
        });

        atceltBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atceltBut.setForeground(new java.awt.Color(255, 153, 153));
        atceltBut.setText("Atcelt");
        atceltBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atceltButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pastsLab2)
                            .addComponent(paroleLab2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pastsText2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paroleText2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ielogBut2)
                        .addGap(18, 18, 18)
                        .addComponent(atceltBut, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastsText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastsLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paroleLab2)
                    .addComponent(paroleText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ielogBut2)
                    .addComponent(atceltBut))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ielogotiesLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ielogotiesLab.setForeground(new java.awt.Color(255, 153, 153));
        ielogotiesLab.setText("Ielogošana");

        javax.swing.GroupLayout IelogošanaLayout = new javax.swing.GroupLayout(Ielogošana.getContentPane());
        Ielogošana.getContentPane().setLayout(IelogošanaLayout);
        IelogošanaLayout.setHorizontalGroup(
            IelogošanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IelogošanaLayout.createSequentialGroup()
                .addGroup(IelogošanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IelogošanaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IelogošanaLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(ielogotiesLab)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        IelogošanaLayout.setVerticalGroup(
            IelogošanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IelogošanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ielogotiesLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        Galvenais_logs.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Galvenais_logs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Galvenais_logsWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        edienkarteBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edienkarteBut.setForeground(new java.awt.Color(255, 153, 153));
        edienkarteBut.setText("Ēdienkarte");
        edienkarteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edienkarteButActionPerformed(evt);
            }
        });

        edienumekBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edienumekBut.setForeground(new java.awt.Color(255, 153, 153));
        edienumekBut.setText("Ēdienu meklēšana");
        edienumekBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edienumekButActionPerformed(evt);
            }
        });

        pasutgrozsBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pasutgrozsBut.setForeground(new java.awt.Color(255, 153, 153));
        pasutgrozsBut.setText("Pasūtījuma grozs");
        pasutgrozsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasutgrozsButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edienumekBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(pasutgrozsBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edienkarteBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(edienkarteBut)
                .addGap(18, 18, 18)
                .addComponent(edienumekBut)
                .addGap(18, 18, 18)
                .addComponent(pasutgrozsBut)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("Restorāns");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 153, 153));
        jButton10.setText("Rediģet ēdienu");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 153, 153));
        jButton11.setText("Pievienot ēdienu");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 153));
        jLabel16.setText("Administratoram");

        javax.swing.GroupLayout Galvenais_logsLayout = new javax.swing.GroupLayout(Galvenais_logs.getContentPane());
        Galvenais_logs.getContentPane().setLayout(Galvenais_logsLayout);
        Galvenais_logsLayout.setHorizontalGroup(
            Galvenais_logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Galvenais_logsLayout.createSequentialGroup()
                .addGroup(Galvenais_logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Galvenais_logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Galvenais_logsLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel15))
                        .addGroup(Galvenais_logsLayout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Galvenais_logsLayout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel16))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        Galvenais_logsLayout.setVerticalGroup(
            Galvenais_logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Galvenais_logsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        Ēdienkarte.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Ēdienkarte.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ĒdienkarteWindowClosing(evt);
            }
        });

        edienkarteLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edienkarteLab.setForeground(new java.awt.Color(255, 153, 153));
        edienkarteLab.setText("Ēdienkarte");

        atpBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atpBut.setForeground(new java.awt.Color(255, 153, 153));
        atpBut.setText("Atpakaļ");
        atpBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpButActionPerformed(evt);
            }
        });

        edienkarteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nosaukums", "Apraksts", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(edienkarteTable);

        idedienamLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idedienamLab.setForeground(new java.awt.Color(255, 153, 153));
        idedienamLab.setText("ID ēdienam:");

        uzgrozuBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uzgrozuBut.setForeground(new java.awt.Color(255, 153, 153));
        uzgrozuBut.setText("Uz grozu");
        uzgrozuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uzgrozuButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ĒdienkarteLayout = new javax.swing.GroupLayout(Ēdienkarte.getContentPane());
        Ēdienkarte.getContentPane().setLayout(ĒdienkarteLayout);
        ĒdienkarteLayout.setHorizontalGroup(
            ĒdienkarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ĒdienkarteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ĒdienkarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ĒdienkarteLayout.createSequentialGroup()
                        .addComponent(atpBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idedienamLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idedienamText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uzgrozuBut))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(ĒdienkarteLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(edienkarteLab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ĒdienkarteLayout.setVerticalGroup(
            ĒdienkarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ĒdienkarteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(edienkarteLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(ĒdienkarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idedienamLab)
                    .addComponent(idedienamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uzgrozuBut)
                    .addComponent(atpBut))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Pasūtījuma_grozs.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Pasūtījuma_grozs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Pasūtījuma_grozsWindowClosing(evt);
            }
        });

        pasutijumaGrozsLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pasutijumaGrozsLab.setForeground(new java.awt.Color(255, 153, 153));
        pasutijumaGrozsLab.setText("Pasūtījuma grozs");

        atpBut4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atpBut4.setForeground(new java.awt.Color(255, 153, 153));
        atpBut4.setText("Atpakaļ");
        atpBut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpBut4ActionPerformed(evt);
            }
        });

        pasutijumaGrozs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ēdiena_ID", "Nosaukums", "Skaits", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(pasutijumaGrozs);

        summaLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        summaLab.setForeground(new java.awt.Color(255, 153, 153));
        summaLab.setText("Summa:       €");

        maksatBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maksatBut.setForeground(new java.awt.Color(255, 153, 153));
        maksatBut.setText("Maksāt");
        maksatBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maksatButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pasūtījuma_grozsLayout = new javax.swing.GroupLayout(Pasūtījuma_grozs.getContentPane());
        Pasūtījuma_grozs.getContentPane().setLayout(Pasūtījuma_grozsLayout);
        Pasūtījuma_grozsLayout.setHorizontalGroup(
            Pasūtījuma_grozsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pasūtījuma_grozsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pasūtījuma_grozsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pasūtījuma_grozsLayout.createSequentialGroup()
                        .addComponent(atpBut4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(summaLab)
                        .addGap(18, 18, 18)
                        .addComponent(maksatBut))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(Pasūtījuma_grozsLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(pasutijumaGrozsLab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pasūtījuma_grozsLayout.setVerticalGroup(
            Pasūtījuma_grozsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pasūtījuma_grozsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pasutijumaGrozsLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(Pasūtījuma_grozsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaLab)
                    .addComponent(maksatBut)
                    .addComponent(atpBut4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Ēdienu_meklēšana.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Ēdienu_meklēšana.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Ēdienu_meklēšanaWindowClosing(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ednosaukumsLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ednosaukumsLab.setForeground(new java.awt.Color(255, 153, 153));
        ednosaukumsLab.setText("Ēdiena nosaukums:");

        ednosaukumsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ednosaukumsTextActionPerformed(evt);
            }
        });

        saglabatBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saglabatBut.setForeground(new java.awt.Color(255, 153, 153));
        saglabatBut.setText("Meklēt");
        saglabatBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saglabatButActionPerformed(evt);
            }
        });

        atpBut1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atpBut1.setForeground(new java.awt.Color(255, 153, 153));
        atpBut1.setText("Atpakaļ");
        atpBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpBut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ednosaukumsLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ednosaukumsText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(saglabatBut, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atpBut1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ednosaukumsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ednosaukumsLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saglabatBut)
                    .addComponent(atpBut1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        edienaNosaukumsLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edienaNosaukumsLab.setForeground(new java.awt.Color(255, 153, 153));
        edienaNosaukumsLab.setText("Ēdiena meklēšana");

        javax.swing.GroupLayout Ēdienu_meklēšanaLayout = new javax.swing.GroupLayout(Ēdienu_meklēšana.getContentPane());
        Ēdienu_meklēšana.getContentPane().setLayout(Ēdienu_meklēšanaLayout);
        Ēdienu_meklēšanaLayout.setHorizontalGroup(
            Ēdienu_meklēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ēdienu_meklēšanaLayout.createSequentialGroup()
                .addGroup(Ēdienu_meklēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ēdienu_meklēšanaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(edienaNosaukumsLab))
                    .addGroup(Ēdienu_meklēšanaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Ēdienu_meklēšanaLayout.setVerticalGroup(
            Ēdienu_meklēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ēdienu_meklēšanaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(edienaNosaukumsLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        Ēdienu_pievienošana.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Ēdienu_pievienošana.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Ēdienu_pievienošanaWindowClosing(evt);
            }
        });

        edPievienosanaLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edPievienosanaLab.setForeground(new java.awt.Color(255, 153, 153));
        edPievienosanaLab.setText("Ēdienu pievienošana");

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        edNosaukumsLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edNosaukumsLab.setForeground(new java.awt.Color(255, 153, 153));
        edNosaukumsLab.setText("Jauna ēdiena nosaukums:");

        edNosaukumsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNosaukumsTextActionPerformed(evt);
            }
        });

        aprakstsLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aprakstsLab.setForeground(new java.awt.Color(255, 153, 153));
        aprakstsLab.setText("Apraksts:");

        aprakstsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprakstsTextActionPerformed(evt);
            }
        });

        cenaLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cenaLab.setForeground(new java.awt.Color(255, 153, 153));
        cenaLab.setText("Cena:");

        cenaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenaTextActionPerformed(evt);
            }
        });

        mekletBut1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mekletBut1.setForeground(new java.awt.Color(255, 153, 153));
        mekletBut1.setText("Saglabāt");
        mekletBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mekletBut1ActionPerformed(evt);
            }
        });

        atpBut2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atpBut2.setForeground(new java.awt.Color(255, 153, 153));
        atpBut2.setText("Atpakaļ");
        atpBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpBut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aprakstsLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aprakstsText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cenaLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(edNosaukumsLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edNosaukumsText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(mekletBut1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(atpBut2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edNosaukumsLab)
                    .addComponent(edNosaukumsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aprakstsLab)
                    .addComponent(aprakstsText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cenaLab)
                    .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atpBut2)
                    .addComponent(mekletBut1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Ēdienu_pievienošanaLayout = new javax.swing.GroupLayout(Ēdienu_pievienošana.getContentPane());
        Ēdienu_pievienošana.getContentPane().setLayout(Ēdienu_pievienošanaLayout);
        Ēdienu_pievienošanaLayout.setHorizontalGroup(
            Ēdienu_pievienošanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ēdienu_pievienošanaLayout.createSequentialGroup()
                .addGroup(Ēdienu_pievienošanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ēdienu_pievienošanaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Ēdienu_pievienošanaLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(edPievienosanaLab)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Ēdienu_pievienošanaLayout.setVerticalGroup(
            Ēdienu_pievienošanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ēdienu_pievienošanaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(edPievienosanaLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Ēdienu_rediģēšana.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Ēdienu_rediģēšana.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Ēdienu_rediģēšanaWindowClosing(evt);
            }
        });

        edRedigesanaLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edRedigesanaLab.setForeground(new java.awt.Color(255, 153, 153));
        edRedigesanaLab.setText("Ēdienu rediģēšana");

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jaunaedNosaukumsLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jaunaedNosaukumsLab.setForeground(new java.awt.Color(255, 153, 153));
        jaunaedNosaukumsLab.setText("Jauna ēdiena nosaukums:");

        jaunaedNosaukumsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaunaedNosaukumsTextActionPerformed(evt);
            }
        });

        jaunsAprakstsLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jaunsAprakstsLab.setForeground(new java.awt.Color(255, 153, 153));
        jaunsAprakstsLab.setText("Jauns apraksts:");

        jaunsAprakstsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaunsAprakstsTextActionPerformed(evt);
            }
        });

        jaunaCenaLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jaunaCenaLab.setForeground(new java.awt.Color(255, 153, 153));
        jaunaCenaLab.setText("Jauna cena:");

        jaunaCenaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaunaCenaTextActionPerformed(evt);
            }
        });

        redigetBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        redigetBut.setForeground(new java.awt.Color(255, 153, 153));
        redigetBut.setText("Rediģēt");
        redigetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redigetButActionPerformed(evt);
            }
        });

        atpBut3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atpBut3.setForeground(new java.awt.Color(255, 153, 153));
        atpBut3.setText("Atpakaļ");
        atpBut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpBut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jaunsAprakstsLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jaunsAprakstsText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jaunaCenaLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jaunaCenaText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jaunaedNosaukumsLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jaunaedNosaukumsText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(redigetBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(atpBut3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jaunaedNosaukumsLab)
                    .addComponent(jaunaedNosaukumsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaunsAprakstsLab)
                    .addComponent(jaunsAprakstsText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaunaCenaLab)
                    .addComponent(jaunaCenaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redigetBut)
                    .addComponent(atpBut3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Ēdienu_rediģēšanaLayout = new javax.swing.GroupLayout(Ēdienu_rediģēšana.getContentPane());
        Ēdienu_rediģēšana.getContentPane().setLayout(Ēdienu_rediģēšanaLayout);
        Ēdienu_rediģēšanaLayout.setHorizontalGroup(
            Ēdienu_rediģēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ēdienu_rediģēšanaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ēdienu_rediģēšanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edRedigesanaLab)
                .addGap(121, 121, 121))
        );
        Ēdienu_rediģēšanaLayout.setVerticalGroup(
            Ēdienu_rediģēšanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ēdienu_rediģēšanaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(edRedigesanaLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        laipniLudzamLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        laipniLudzamLab.setForeground(new java.awt.Color(255, 153, 153));
        laipniLudzamLab.setText("Laipni lūdzam!");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ielogBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ielogBut.setForeground(new java.awt.Color(255, 153, 153));
        ielogBut.setText("Ielogoties");
        ielogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ielogButActionPerformed(evt);
            }
        });

        registrBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrBut.setForeground(new java.awt.Color(255, 153, 153));
        registrBut.setText("Reģistrēties");
        registrBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrBut)
                    .addComponent(ielogBut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ielogBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrBut)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Lūdzu, reģistrējieties vai piesakieties savā kontā, ");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("pirms sākat lietot mūsu lietotni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(laipniLudzamLab))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(laipniLudzamLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ielogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ielogButActionPerformed
        // TODO add your handling code here:
           Ielogošana.setBounds(650,300,350,300);
Ielogošana.setVisible(true);
        this.setVisible(false);
        


    }//GEN-LAST:event_ielogButActionPerformed

    private void pastsText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastsText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastsText2ActionPerformed

    private void paroleText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paroleText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paroleText2ActionPerformed

    private void ielogBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ielogBut2ActionPerformed
        // TODO add your handling code here:
        
             Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
        Ielogošana.setVisible(false);
    }//GEN-LAST:event_ielogBut2ActionPerformed

    private void atceltButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atceltButActionPerformed
        // TODO add your handling code here:
               this.setVisible(true);
     Ielogošana.setVisible(false); 
        
    }//GEN-LAST:event_atceltButActionPerformed

    private void edienkarteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edienkarteButActionPerformed
        // TODO add your handling code here:
        
             Ēdienkarte.setBounds(650,300,350,550);
Ēdienkarte.setVisible(true);
        Galvenais_logs.setVisible(false);
        
    }//GEN-LAST:event_edienkarteButActionPerformed

    private void edienumekButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edienumekButActionPerformed
        // TODO add your handling code here:
        
                   Ēdienu_meklēšana.setBounds(650,300,350,250);
Ēdienu_meklēšana.setVisible(true);
        Galvenais_logs.setVisible(false);
        
    }//GEN-LAST:event_edienumekButActionPerformed

    private void pasutgrozsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasutgrozsButActionPerformed
        // TODO add your handling code here:
              Pasūtījuma_grozs.setBounds(650,350,350,550);
Pasūtījuma_grozs.setVisible(true);
        Galvenais_logs.setVisible(false);
    }//GEN-LAST:event_pasutgrozsButActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
                        Ēdienu_rediģēšana.setBounds(650,300,400,300);
        Ēdienu_rediģēšana.setVisible(true);
        Galvenais_logs.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          Ēdienu_pievienošana.setBounds(650,300,400,300);
        Ēdienu_pievienošana.setVisible(true);
        Galvenais_logs.setVisible(false);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void vardsText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vardsText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vardsText3ActionPerformed

    private void uzvardsText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uzvardsText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uzvardsText3ActionPerformed

    private void talrunisText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talrunisText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talrunisText3ActionPerformed

    private void pastsText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastsText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastsText4ActionPerformed

    private void paroleText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paroleText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paroleText4ActionPerformed

    private void atceltBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atceltBut1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
     Reģistrēšana.setVisible(false); 
    }//GEN-LAST:event_atceltBut1ActionPerformed

    private void atpButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpButActionPerformed


           Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
     Ēdienkarte.setVisible(false); 
    }//GEN-LAST:event_atpButActionPerformed

    private void uzgrozuButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uzgrozuButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uzgrozuButActionPerformed

    private void ednosaukumsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ednosaukumsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ednosaukumsTextActionPerformed

    private void saglabatButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saglabatButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saglabatButActionPerformed

    private void atpBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpBut1ActionPerformed
        // TODO add your handling code here:
        
           Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
     Ēdienu_meklēšana.setVisible(false); 
    }//GEN-LAST:event_atpBut1ActionPerformed

    private void cenaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cenaTextActionPerformed

    private void aprakstsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprakstsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprakstsTextActionPerformed

    private void edNosaukumsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNosaukumsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNosaukumsTextActionPerformed

    private void mekletBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mekletBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mekletBut1ActionPerformed

    private void atpBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpBut2ActionPerformed
        // TODO add your handling code here:
                 Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
     Ēdienu_pievienošana.setVisible(false); 
    }//GEN-LAST:event_atpBut2ActionPerformed

    private void jaunaedNosaukumsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaunaedNosaukumsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaunaedNosaukumsTextActionPerformed

    private void jaunsAprakstsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaunsAprakstsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaunsAprakstsTextActionPerformed

    private void jaunaCenaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaunaCenaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaunaCenaTextActionPerformed

    private void redigetButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redigetButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redigetButActionPerformed

    private void atpBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpBut3ActionPerformed
        // TODO add your handling code here:
           Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
     Ēdienu_rediģēšana.setVisible(false); 
    }//GEN-LAST:event_atpBut3ActionPerformed

    private void atpBut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpBut4ActionPerformed
        // TODO add your handling code here:
            Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
     Pasūtījuma_grozs.setVisible(false); 
    }//GEN-LAST:event_atpBut4ActionPerformed

    private void maksatButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maksatButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maksatButActionPerformed

    private void registrButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrButActionPerformed
        // TODO add your handling code here:
              Reģistrēšana.setBounds(650,300,350,400);
Reģistrēšana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrButActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
   
        int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    

    }//GEN-LAST:event_formWindowClosing

    private void ReģistrēšanaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ReģistrēšanaWindowClosing
   int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
        


    }//GEN-LAST:event_ReģistrēšanaWindowClosing

    private void registrBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrBut3ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
    Galvenais_logs.setBounds(650,300,350,450);
Galvenais_logs.setVisible(true);
        Reģistrēšana.setVisible(false);
    }//GEN-LAST:event_registrBut3ActionPerformed

    private void IelogošanaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_IelogošanaWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_IelogošanaWindowClosing

    private void Galvenais_logsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Galvenais_logsWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_Galvenais_logsWindowClosing

    private void ĒdienkarteWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ĒdienkarteWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_ĒdienkarteWindowClosing

    private void Pasūtījuma_grozsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Pasūtījuma_grozsWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_Pasūtījuma_grozsWindowClosing

    private void Ēdienu_meklēšanaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Ēdienu_meklēšanaWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_Ēdienu_meklēšanaWindowClosing

    private void Ēdienu_pievienošanaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Ēdienu_pievienošanaWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_Ēdienu_pievienošanaWindowClosing

    private void Ēdienu_rediģēšanaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Ēdienu_rediģēšanaWindowClosing
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(
            Registresana.this,
            "Vai tiešām vēlaties aizvērt lietotni?",
            "Apstiprinājums",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    
    }//GEN-LAST:event_Ēdienu_rediģēšanaWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registresana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registresana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registresana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registresana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registresana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Galvenais_logs;
    private javax.swing.JDialog Ielogošana;
    private javax.swing.JDialog Pasūtījuma_grozs;
    private javax.swing.JDialog Reģistrēšana;
    private javax.swing.JLabel aprakstsLab;
    private javax.swing.JTextField aprakstsText;
    private javax.swing.JButton atceltBut;
    private javax.swing.JButton atceltBut1;
    private javax.swing.JButton atpBut;
    private javax.swing.JButton atpBut1;
    private javax.swing.JButton atpBut2;
    private javax.swing.JButton atpBut3;
    private javax.swing.JButton atpBut4;
    private javax.swing.JLabel cenaLab;
    private javax.swing.JTextField cenaText;
    private javax.swing.JLabel edNosaukumsLab;
    private javax.swing.JTextField edNosaukumsText;
    private javax.swing.JLabel edPievienosanaLab;
    private javax.swing.JLabel edRedigesanaLab;
    private javax.swing.JLabel edienaNosaukumsLab;
    private javax.swing.JButton edienkarteBut;
    private javax.swing.JLabel edienkarteLab;
    private javax.swing.JTable edienkarteTable;
    private javax.swing.JButton edienumekBut;
    private javax.swing.JLabel ednosaukumsLab;
    private javax.swing.JTextField ednosaukumsText;
    private javax.swing.JLabel idedienamLab;
    private javax.swing.JTextField idedienamText;
    private javax.swing.JButton ielogBut;
    private javax.swing.JButton ielogBut2;
    private javax.swing.JLabel ielogotiesLab;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jaunaCenaLab;
    private javax.swing.JTextField jaunaCenaText;
    private javax.swing.JLabel jaunaedNosaukumsLab;
    private javax.swing.JTextField jaunaedNosaukumsText;
    private javax.swing.JLabel jaunsAprakstsLab;
    private javax.swing.JTextField jaunsAprakstsText;
    private javax.swing.JLabel laipniLudzamLab;
    private javax.swing.JButton maksatBut;
    private javax.swing.JButton mekletBut1;
    private javax.swing.JLabel paroleLab2;
    private javax.swing.JLabel paroleLab4;
    private javax.swing.JTextField paroleText2;
    private javax.swing.JTextField paroleText4;
    private javax.swing.JLabel pastsLab2;
    private javax.swing.JLabel pastsLab4;
    private javax.swing.JTextField pastsText2;
    private javax.swing.JTextField pastsText4;
    private javax.swing.JButton pasutgrozsBut;
    private javax.swing.JTable pasutijumaGrozs;
    private javax.swing.JLabel pasutijumaGrozsLab;
    private javax.swing.JButton redigetBut;
    private javax.swing.JButton registrBut;
    private javax.swing.JButton registrBut3;
    private javax.swing.JLabel registrLab1;
    private javax.swing.JButton saglabatBut;
    private javax.swing.JLabel summaLab;
    private javax.swing.JLabel talrunisLab3;
    private javax.swing.JTextField talrunisText3;
    private javax.swing.JButton uzgrozuBut;
    private javax.swing.JLabel uzvardsLab3;
    private javax.swing.JTextField uzvardsText3;
    private javax.swing.JLabel vardsLab3;
    private javax.swing.JTextField vardsText3;
    private javax.swing.JDialog Ēdienkarte;
    private javax.swing.JDialog Ēdienu_meklēšana;
    private javax.swing.JDialog Ēdienu_pievienošana;
    private javax.swing.JDialog Ēdienu_rediģēšana;
    // End of variables declaration//GEN-END:variables
}
